### ISSUE TITLE
Single location for binaries

### ISSUE THREAD

**Issue by jblindsay** [giswqs/whitebox-bin#1]
@giswqs We are hoping to have the binaries for WhiteboxTools hosted on in a single location on the Whitebox homepage rather than in multiple locations around the web. This has been a problem for the project in the past and I would ask that you please consider using our location to grab these binaries instead.

**Comment by giswqs** [comment]
@jblindsay Sorry for the confusion. I originally used the links to the binaries hosted on your GitHub repo. Since you have moved the binaries to whiteboxgeo.com, I updated the links for the whitebox package for v1.5.0 (see https://github.com/giswqs/whitebox-python/commit/cf80555c2d4b17b492a36c1fb7f491ba4db1bfe3). However, the repo failed to pass the automated testing due to random errors resulting from connection timeout. Check out the links and screenshots below. I am not sure if whiteboxgeo.com has some restrictions regarding the automated download of binaries. Any advice?

I also updated the Linux binary (compiled using Ubuntu 18.04 LTS) so that it can be used on Google Colab. 

https://github.com/giswqs/whitebox-python/actions

![](https://i.imgur.com/VrbL1Yz.png)
![](https://i.imgur.com/4OPfr81.png)

**Comment by giswqs** [comment]
I just switched the binary URLs back to whiteboxgeo.com. It seems the connection timeout errors no longer occur. Not sure why it failed for v1.5.0
https://github.com/giswqs/whitebox-python/commit/970db893ebc9800f69ec95307f8f15ee8785048d

**Comment by jblindsay** [comment]
@giswqs Do you need the full address of each of the three binaries? I'm happy to provide.

**Comment by giswqs** [comment]
It is already using the direct URLs to each binary. Before I delete this repo, could you consider updating the Linux binary on whiteboxgeo.com? The one you released requires GLIBC 2.29, which is not compatible with Ubuntu 18.04 LTS and Google Colab. I complied WBT from source using the [Colab notebook](https://colab.research.google.com/drive/16zd5-8pKx4nw8USRAJsK8wxe2B-1OZsA). I then replaced the `whitebox_tools` Linux binary within your zip file. All other files remain the same. This can resolve the issues as mentioned in https://github.com/jblindsay/whitebox-tools/discussions/189

Updated Linux binary: https://github.com/giswqs/whitebox-bin/raw/master/WhiteboxTools_linux_amd64.zip

https://github.com/giswqs/whitebox-python/commit/970db893ebc9800f69ec95307f8f15ee8785048d
![](https://i.imgur.com/sGBT257.png)

**Comment by jblindsay** [comment]
I just updated the binary. What I don't understand about this is that the current LTS version of Ubuntu is 20.04, which is what I build on. Why do we need to support an outdated LTS version rather than the current one? Isn't that the point of a LTS version?

**Comment by giswqs** [comment]
All WBT frontends now use binary URLs from WhiteboxGeo.com. This repo will no longer be updated.

**Comment by jblindsay** [comment]
@giswqs Thanks Qiusheng!
